# Generated by Django 5.0.1 on 2024-02-27 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('number_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('derpartment', models.CharField(default='DEFAULT_DEPARTMENT', max_length=100)),
                ('year', models.CharField(default='DEFAULT_YEAR', max_length=100)),
                ('date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=50)),
                ('Marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PRN', models.CharField(default='DEFAULT_PRN', max_length=100)),
                ('Roll_number', models.CharField(default='DEFAULT_ROLL_NUMBER')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=100, null=True)),
                ('Father_contact', models.CharField(max_length=15, null=True)),
                ('Mother_name', models.CharField(max_length=100, null=True)),
                ('Mother_contact', models.CharField(max_length=15, null=True)),
                ('Year', models.CharField(default='DEFAULT_CLASS', max_length=50)),
                ('Department', models.CharField(default='DEFAULT_DEPARTMENT', max_length=50)),
                ('division', models.CharField(default='DEFAULT_DIVISION', max_length=50)),
                ('Category', models.CharField(default='DEFAULT_CATEGORY', max_length=50)),
                ('Admission_quota', models.CharField(default='DEFAULT_ADMISSION_QUOTA', max_length=50)),
                ('Email_id', models.EmailField(max_length=254, null=True)),
                ('Mobile_number', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectDepartment', models.CharField(default='DEFAULT_DEPARTMENT', max_length=50)),
                ('SubjectSemester', models.CharField(default='DEFAULT_SEMESTER', max_length=50)),
                ('SubjectYear', models.CharField(default='DEFAULT_YEAR', max_length=50)),
                ('SubjectName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacherid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=50)),
                ('year', models.CharField(default='DEFAULT_YEAR', max_length=50)),
                ('division', models.CharField(default='DEFAULT_DIVISION', max_length=50)),
                ('timetable', models.TextField(default='DEFAULT_TIMETABLE', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('FeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Received_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Due_date', models.CharField(default='DEFAULT_DUE_DATE', max_length=50)),
                ('Year', models.CharField(default='DEFAULT_YEAR', max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Timeto', models.CharField(default='DEFAULT_TIME', max_length=50)),
                ('Timefrom', models.CharField(default='DEFAULT_TIME', max_length=50)),
                ('SubjectName', models.CharField(default='DEFAULT_SUBJECT_NAME', max_length=50)),
                ('Status', models.BooleanField(max_length=50)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.student')),
                ('SubjectID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_1.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_date', models.DateField()),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.class')),
                ('class_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='erp_1.teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='erp_1.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Subject_Assignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.subject')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.teacher')),
            ],
        ),
    ]
