# Generated by Django 5.0.4 on 2024-07-18 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('YearID', models.AutoField(primary_key=True, serialize=False)),
                ('YearName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=255, unique=True)),
                ('DepartmentID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_1.department')),
                ('YearID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.year')),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='')),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('HODID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=255, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.department')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PRN', models.CharField(max_length=255, unique=True)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('AdharNumber', models.CharField(default='none', max_length=255)),
                ('DOB', models.DateField(default='none')),
                ('Gender', models.CharField(default='none', max_length=50)),
                ('Category', models.CharField(default='none', max_length=200)),
                ('Bloodgrp', models.CharField(default='none', max_length=20)),
                ('tempadd', models.CharField(default='none', max_length=255)),
                ('permenentadd', models.CharField(default='none', max_length=255)),
                ('FatherName', models.CharField(blank=True, max_length=255, null=True)),
                ('FatherContact', models.CharField(blank=True, max_length=255, null=True)),
                ('MotherName', models.CharField(blank=True, max_length=255, null=True)),
                ('MotherContact', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('MobileNumber', models.CharField(max_length=255, unique=True)),
                ('RollNumber', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('AdmissionQuota', models.CharField(default='none', max_length=255)),
                ('YearDownStatus', models.BooleanField(default=False)),
                ('CurrentClassID', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('RoleID', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='erp_1.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('FeeID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ReceivedAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], max_length=50)),
                ('DueDate', models.DateField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.student')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('AlumniID', models.AutoField(primary_key=True, serialize=False)),
                ('GraduationDate', models.DateField()),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('ContactNumber', models.CharField(max_length=255, unique=True)),
                ('LastClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgression',
            fields=[
                ('ProgressionID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Status', models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed'), ('Year Down', 'Year Down')], max_length=50)),
                ('YearDownReason', models.TextField(blank=True, null=True)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=255)),
                ('SubjectSemester', models.IntegerField()),
                ('SubjectType', models.CharField(choices=[('Theoretical', 'Theoretical'), ('Practical', 'Practical')], max_length=50)),
                ('SubjectBatch', models.CharField(max_length=255)),
                ('CurrentClassID', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False)),
                ('Marks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.student')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('BacklogID', models.AutoField(primary_key=True, serialize=False)),
                ('BacklogDate', models.DateField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared')], max_length=50)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.student')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Timeto', models.CharField(default='DEFAULT_TIME', max_length=50)),
                ('Timefrom', models.CharField(default='DEFAULT_TIME', max_length=50)),
                ('Status', models.BooleanField(max_length=50)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.student')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacherid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=255, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.department')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.roles')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('AssignmentDate', models.DateField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.roles')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Subject_Assignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.subject')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('TimetableID', models.AutoField(primary_key=True, serialize=False)),
                ('Division', models.CharField(max_length=255)),
                ('Timetable', models.TextField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.department')),
            ],
        ),
    ]
