# Generated by Django 5.0.4 on 2024-07-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='SubjectDepartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_1.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='SubjectYear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_1.year'),
        ),
    ]
