# Generated by Django 5.0.4 on 2024-07-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0002_subject_subjectdepartment_subject_subjectyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='SubjectDepartment',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='SubjectYear',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
