# Generated by Django 5.0.1 on 2024-02-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0002_student_create_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notices',
        ),
    ]
