# Generated by Django 5.0.1 on 2024-02-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0003_delete_notices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('derpartment', models.CharField(default='DEFAULT_DEPARTMENT', max_length=100)),
                ('year', models.CharField(default='DEFAULT_YEAR', max_length=100)),
                ('date', models.DateField()),
                ('attachment', models.FileField(blank=True, upload_to='notices/attachments/')),
            ],
        ),
    ]
