# Generated by Django 5.0.4 on 2024-07-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0003_alter_subject_subjectdepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='SubjectName',
            field=models.CharField(default='DEFAULT_SUBJECT_NAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='SubjectID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_1.subject'),
        ),
    ]
