# Generated by Django 5.0.1 on 2024-02-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0004_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='notices/attachments/'),
        ),
    ]
