# Generated by Django 5.0.4 on 2024-07-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0004_attendance_subjectname_alter_attendance_subjectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CurrentClassID',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='RoleID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp_1.roles'),
        ),
    ]
