# Generated by Django 5.0.4 on 2024-07-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0005_alter_student_currentclassid_alter_student_roleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteacherassignment',
            name='TeacherID',
        ),
    ]
