# Generated by Django 5.0.1 on 2024-03-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0005_alter_notices_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='SubjectType',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='notices',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
