# Generated by Django 5.0.4 on 2024-07-25 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0006_remove_classteacherassignment_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacherassignment',
            name='TeacherID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erp_1.teacher'),
            preserve_default=False,
        ),
    ]
