# Generated by Django 5.0.1 on 2024-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0006_subject_subjecttype_alter_notices_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Batch',
            field=models.CharField(default='DEFAULT_BATCH', max_length=50),
        ),
    ]
