# Generated by Django 5.0.4 on 2024-07-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0008_alter_classteacherassignment_teacherid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteacherassignment',
            name='AssignmentDate',
        ),
        migrations.RemoveField(
            model_name='classteacherassignment',
            name='TeacherID',
        ),
    ]
