# Generated by Django 5.0.1 on 2024-03-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0008_alter_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Subjectbatch',
            field=models.CharField(default='DEFAULT_BATCH', max_length=50),
        ),
    ]
