# Generated by Django 5.0.4 on 2024-07-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0009_remove_classteacherassignment_assignmentdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTeacherAssignment',
        ),
    ]
