# Generated by Django 5.0.4 on 2024-07-25 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0010_delete_classteacherassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.roles')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.teacher')),
            ],
        ),
    ]
