# Generated by Django 5.0.4 on 2024-07-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0011_classteacherassignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_Subject_Assignment',
            new_name='TeacherSubjectAssignment',
        ),
    ]
