# Generated by Django 5.0.4 on 2024-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0012_rename_teacher_subject_assignment_teachersubjectassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='DepartmentID',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Division',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Timetable',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
