# Generated by Django 5.0.4 on 2024-08-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0013_remove_timetable_departmentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='ClassID',
        ),
    ]
