# Generated by Django 5.0.4 on 2024-08-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0014_remove_attendance_classid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ClassID',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes'),
        ),
    ]
