# Generated by Django 5.0.4 on 2024-08-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0017_subject_subjectyr_alter_subject_subjectdep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Subjectdep',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Subjectyr',
        ),
    ]
