# Generated by Django 5.0.4 on 2024-08-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0019_subject_subjectdep_subject_subjectyr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='SubjectType',
            field=models.CharField(choices=[('Theoretical', 'Theoretical'), ('Practical', 'Practical')], max_length=51),
        ),
    ]
