# Generated by Django 5.0.4 on 2024-08-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0020_alter_subject_subjecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='SubjectType',
            field=models.CharField(choices=[('Theoretical', 'Theoretical'), ('Practical', 'Practical')], max_length=50),
        ),
    ]
