# Generated by Django 5.0.4 on 2024-08-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0021_alter_subject_subjecttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='SubjectType',
        ),
    ]
