# Generated by Django 5.0.4 on 2024-08-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0022_remove_subject_subjecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='SubjectType',
            field=models.BooleanField(default=True, max_length=50),
        ),
    ]
