# Generated by Django 5.0.4 on 2024-08-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0025_remove_notices_description_notices_teacherpublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notices',
            name='teacherpublished',
        ),
    ]
