# Generated by Django 5.0.4 on 2024-08-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0027_notices_teacherpublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='AdharNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='AdmissionQuota',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Bloodgrp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='FatherContact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='MotherContact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='MotherName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='PRN',
        ),
        migrations.RemoveField(
            model_name='student',
            name='YearDownStatus',
        ),
        migrations.RemoveField(
            model_name='student',
            name='permenentadd',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tempadd',
        ),
    ]
