# Generated by Django 5.0.4 on 2024-08-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0028_remove_student_adharnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PRN',
            field=models.IntegerField(default=102012),
        ),
    ]
