# Generated by Django 5.0.4 on 2024-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0029_student_prn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PRN',
            field=models.CharField(default=102012, max_length=255),
        ),
    ]
