# Generated by Django 5.0.4 on 2024-08-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0031_alter_student_prn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Gender',
        ),
    ]
