# Generated by Django 5.0.4 on 2024-08-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0032_remove_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='attachment',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
