# Generated by Django 5.0.4 on 2024-08-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0033_alter_notices_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='FatherName',
        ),
    ]
