# Generated by Django 5.0.4 on 2024-10-14 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0034_remove_student_fathername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('Slotid', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(default='DEFAULT_TIME', max_length=50)),
                ('end_time', models.CharField(default='DEFAULT_TIME', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='SubjectAssignmentID',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='erp_1.teachersubjectassignment'),
        ),

    ]
