# Generated by Django 5.0.4 on 2024-10-14 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0035_slots_remove_timetable_timetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='SlotID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_1.slots'),
        ),
    ]
