# Generated by Django 5.0.4 on 2024-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0036_timetable_slotid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Day',
            field=models.CharField(default='Monday', max_length=255),
        ),
    ]
