# Generated by Django 5.0.4 on 2024-10-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0037_timetable_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('Batchid', models.AutoField(primary_key=True, serialize=False)),
                ('BatchName', models.CharField(default='Batch', max_length=50)),
                ('class_id', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
            ],
        ),
    ]
