# Generated by Django 5.0.4 on 2024-10-16 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0039_timetable_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Batch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp_1.batch'),
        ),
    ]
