# Generated by Django 5.0.4 on 2024-10-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0040_alter_timetable_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='Batch',
        ),
    ]
