# Generated by Django 4.1.7 on 2024-11-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0043_attendance_slotid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('LeaveTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('LeaveTypeName', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='slots',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slots',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('LeaveRequestID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Reason', models.TextField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('RequestDate', models.DateTimeField(auto_now_add=True)),
                ('ApprovalDate', models.DateTimeField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('LeaveTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.leavetype')),
                ('RequestedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals', to='erp_1.teacher')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='erp_1.teacher')),
            ],
        ),
    ]
