# Generated by Django 5.0.4 on 2024-12-29 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0044_leavetype_alter_slots_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='Comments',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='TeacherTimeSlot',
            fields=[
                ('TimeSlotID', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.CharField(max_length=50)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.classes')),
                ('SlotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.slots')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_1.teacher')),
            ],
        ),
    ]
