# Generated by Django 5.0.4 on 2024-12-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0045_remove_leaverequest_comments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherTimeSlot',
            new_name='TempTimetable',
        ),
    ]
