# Generated by Django 5.0.4 on 2024-12-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0046_rename_teachertimeslot_temptimetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptimetable',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='temptimetable',
            name='StartTime',
        ),
    ]
