# Generated by Django 5.0.4 on 2024-12-29 16:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0047_remove_temptimetable_endtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temptimetable',
            old_name='TeacherID',
            new_name='ReplacementTeacherID',
        ),
        migrations.RemoveField(
            model_name='temptimetable',
            name='Day',
        ),
        migrations.AddField(
            model_name='temptimetable',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='temptimetable',
            name='LeaveRequestID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_1.leaverequest'),
        ),
        migrations.AlterModelTable(
            name='temptimetable',
            table='TempTimetable',
        ),
    ]
