# Generated by Django 5.0.4 on 2024-12-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0048_rename_teacherid_temptimetable_replacementteacherid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='HODApprovalDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='PrincipalApprovalDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_approvedByHOD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_approvedByPrincipal',
            field=models.BooleanField(default=False),
        ),
    ]
