# Generated by Django 5.0.4 on 2024-12-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0049_leaverequest_hodapprovaldate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temptimetable',
            table=None,
        ),
    ]
