# Generated by Django 5.0.4 on 2024-12-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0050_alter_temptimetable_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending Principal Approval', 'Pending Principal Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
