# Generated by Django 5.0.4 on 2025-01-02 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0051_alter_leaverequest_status'),
    ]

    operations = [
       migrations.RemoveField(
            model_name='temptimetable',
            name='ReplacementTeacherID',
        ),
    ]
    