# Generated by Django 5.0.4 on 2025-01-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_1', '0052_alter_temptimetable_replacementteacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptimetable',
            name='ReplacementTeacherID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_1.teachersubjectassignment'),
        ),
    ]
